# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

#  - OpenCraft Studios Team

name: Generate artifacts

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Download JDK 1.8
      id: compile
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
    
    - name: Compile client
      run: mvn -B package --file pom.xml
      env:
        MAVEN_USERNAME: CiroZDP
        MAVEN_PASSWORD: ${{ secrets.SECRET_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.SECRET_TOKEN }}
      
    - uses: ./.github/actions/upload_build
      if: ${{ always() && steps.compile.outcome == 'success' }}
      with:
        SOURCE_FILE: 'target/client.jar'
        DEST_NAME: 'client.jar'
